name: SpiderWeb CI/CD

on:
  push:
    branches: [dev]
  workflow_dispatch:
    inputs:
      option:
        description: "Choose option to run"
        required: true
        default: "option1"
        type: choice
        options:
          - option1
          - option2
          - option3

jobs:
  run-software:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run Python Script
        run: |
          python test.py ${{ github.event.inputs.option }}
