name: SpiderWeb CI/CD

on:
  push:
    branches: [dev]
    inputs:
      option:
        description: "Choose option to run"
        required: true
        default: "option1"
        type: choice
        options:
          - option1
          - option2
          - option3
jobs:
  run-software:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python Script
        run: |
          python main.py ${{ github.event.inputs.option }}
